# Generated by Django 4.0.3 on 2022-04-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttackInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AttackTitle', models.CharField(default='', max_length=70)),
                ('Attackdescription', models.CharField(default='', max_length=400)),
            ],
        ),
    ]
