# Generated by Django 4.0.3 on 2022-04-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HackademyAPI', '0002_alter_attackinfo_attacktitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachinesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MachineNumber', models.IntegerField()),
                ('MachineName', models.CharField(max_length=70)),
                ('MachineType', models.CharField(max_length=70)),
                ('MachineLaunchDate', models.DateField()),
                ('MachineExpiryDate', models.DateField()),
                ('MachineDescription', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='attackinfo',
            name='Attackdescription',
        ),
        migrations.AddField(
            model_name='attackinfo',
            name='AttackDescription',
            field=models.CharField(default='', max_length=200),
        ),
    ]
