# Generated by Django 4.0.3 on 2022-05-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HackademyAPI', '0003_machinesinfo_remove_attackinfo_attackdescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryTitle', models.CharField(max_length=70)),
                ('CategoryDescription', models.TextField(default='')),
                ('Challenge1Description', models.TextField(default='')),
                ('Challenge2Description', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='attackinfo',
            name='AttackDescription',
            field=models.TextField(default=''),
        ),
    ]
