# Generated by Django 4.0.3 on 2022-06-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HackademyAPI', '0005_machinesinfo_machinetitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MachineName', models.CharField(max_length=70)),
            ],
        ),
    ]
